config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get "/sessions/current" => "ember_devise_simple_auth/sessions#show"
  end

  namespace :api do
    resources :companies
    resources :projects
    resources :users, only: [:index, :show, :create]
  end

  root to: 'assets#index'
  
  devise_for :users, controllers: { sessions: 'ember_devise_simple_auth/sessions' }
  
  get '*path', to: 'assets#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :projects, dependent: :destroy
  belongs_to :user

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies

  validates_presence_of :first_name, :last_name

end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < ApplicationController
  respond_to :json

  def index
    respond_with Company.all
  end

  def show
    respond_with company
  end

  def create
    respond_with :api, Company.create(company_params)
  end

  def update
    respond_with company.update(company_params)
  end

  def destroy
    respond_with company.destroy
  end

  private

  def company
    Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, 
                                    :description, 
                         projects: [:name, :description, :company_id])
  end

end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  respond_to :json

  def index
    respond_with Project.all
  end

  def show
    respond_with project
  end

  def create
    respond_with :api, Project.create(project_params)
  end

  def update
    respond_with project.update(project_params)
  end

  def destroy
    respond_with project.destroy
  end

  private

  def project
    Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :company_id)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  respond_to :json

  def index
    respond_with User.all
  end

  def show
    respond_with user
  end

  def create
    respond_with :api, User.create(user_params)
  end

  def update
    respond_with user.update(user)
  end

  def destroy
    respond_with user.destroy
  end

  private

  def user
    User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,       
                                  :last_name, 
                                  :email, 
                                  :password, 
                                  companies: 
                                      [:name, 
                                      :description, 
                                      :user_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  end

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]



  def index
    @companies = Company.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private
    
    def company_params
      params.require(:company).permit(:name, :description, :user_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

    def project_params
      params.require(:project).permit(:name, :description, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def user_name(obj)
  "#{obj.user.first_name} " + "#{obj.user.last_name}" 
  end

end

app/views/companies/_form.html.haml
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th Name
    %th Description
    %th User/Owner
    %th Edit options
    %th

  - @companies.each do |company|
    %tr
      %td= company.name
      %td= company.description
      %td= user_name(company)
      - if current_user == company.user
        %td= link_to 'Show', company
        %td= link_to 'Edit', edit_company_path(company)
        %td= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }
      - else
        %td Only company owner can edit a company.

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @company.name
%p
  %b Description:
  = @company.description

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %title Ember with Rails. Ninja!
    = csrf_meta_tags
    = stylesheet_link_tag 'application' 
    = javascript_include_tag 'application', media: 'all'
    = csrf_meta_tags

  %body
    = yield

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :company
    = f.text_field :company
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Description
    %th Company
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.description
      %td= project.company
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name
%p
  %b Description:
  = @project.description
%p
  %b Company:
  = @project.company

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path